### ISSUE TITLE
Missing countries in Mobility data

### ISSUE THREAD

**Issue by arthur2020-ca** [horaceg/covid19-analysis#1]
Thank you so much for your work in the "mobility" project. I’m using this to better understand the impact of social distancing on COVID-19 cases.

As I was working with the data, I noticed that Hong Kong is missing from the dataset. I went to Google site (https://www.google.com/covid19/mobility/) and identified all of the country codes that Google has in the files and compared it with the codes in your file “download.sh”

I’ve identified the following countries and U.S. states as missing:

Greece	GR
Hong Kong	HK
Namibia	NA
Réunion	RE
Tajikistan	TJ
Yemen	YE

United States: District_of_Columbia

It would be great if you could add these into your code and refresh the data.

Thank you again!

Arthur

**Comment by horaceg** [comment]
Hello Arthur,

I am glad you find a use for this data !

Thank you for listing these countries.
I just updated the data, they should appear in current version of it.

Cheers,
Horace
