### ISSUE TITLE
Only 11 Regions out of 26 are available in Switzerland

### ISSUE THREAD

**Issue by Majoul** [horaceg/covid19-analysis#3]
Hello 
Thank you so much for this 
I' am not sure if this also happen for other contries but i noticed that only 11 regions out of 26 are available in Switzerland 
Thank you

**Comment by horaceg** [comment]
Hi,

Indeed some regions are missing in Switzerland. This might be because there is not enough data in some charts. I'll take a look at the parsing for these regions.
